// This code was generated by Rumpelstiltskin
// Do not modify anything by hand and run the main.swift skript instead
import Foundation
struct Localization {
    struct Accessibility {
        /// Base translation: Button %@
        public static func Button(value1: String) -> String {
            return String(format: NSLocalizedString("Localization.Accessibility.Button", tableName: nil, bundle: Bundle.main, value: "", comment: "")
            , value1)
        }
        /// Base translation: Accessibility
        public static let Example1 = NSLocalizedString("Localization.Accessibility.Example1", tableName: nil, bundle: Bundle.main, value: "", comment: "")
        /// Base translation: Image %@
        public static func Image(value1: String) -> String {
            return String(format: NSLocalizedString("Localization.Accessibility.Image", tableName: nil, bundle: Bundle.main, value: "", comment: "")
            , value1)
        }
        /// Base translation: Preview %d
        public static func Preview(value1: Int) -> String {
            return String(format: NSLocalizedString("Localization.Accessibility.Preview", tableName: nil, bundle: Bundle.main, value: "", comment: "")
            , value1)
        }
        /// Base translation: Thumbnail %d
        public static func ThumbnailImage(value1: Int) -> String {
            return String(format: NSLocalizedString("Localization.Accessibility.ThumbnailImage", tableName: nil, bundle: Bundle.main, value: "", comment: "")
            , value1)
        }
    }
    struct Application {
        /// Base translation: Version: %@
        public static func Version(value1: String) -> String {
            return String(format: NSLocalizedString("Localization.Application.Version", tableName: nil, bundle: Bundle.main, value: "", comment: "")
            , value1)
        }
    }
    struct Buttons {
        /// Base translation: Some Example Text
        public static let Example = NSLocalizedString("Localization.Buttons.Example", tableName: nil, bundle: Bundle.main, value: "", comment: "")
        /// Base translation: Wow amazing button
        public static let Number2 = NSLocalizedString("Localization.Buttons.Number2", tableName: nil, bundle: Bundle.main, value: "", comment: "")
    }
    struct Login {
        /// Base translation: Password
        public static let Password = NSLocalizedString("Localization.Login.Password", tableName: nil, bundle: Bundle.main, value: "", comment: "")
        /// Base translation: Username
        public static let Username = NSLocalizedString("Localization.Login.Username", tableName: nil, bundle: Bundle.main, value: "", comment: "")
    }
    struct LongerText {
        /// Base translation: This is supposed to be longer text that includes some line breaks \n but is not formatted by using multi line string.  \n\n Multi line strings are currently not supported \n\n I'm sorry...
        public static let NoMultiline = NSLocalizedString("Localization.LongerText.NoMultiline", tableName: nil, bundle: Bundle.main, value: "", comment: "")
    }
    struct Menu {
        struct Toast {
            /// Base translation: Downloading. %d Please wait
            public static func Downloading(value1: Int) -> String {
                return String(format: NSLocalizedString("Localization.Menu.Toast.Downloading", tableName: nil, bundle: Bundle.main, value: "", comment: "")
                , value1)
            }
            /// Base translation: Preparing to download %d
            public static func Preparing(value1: Int) -> String {
                return String(format: NSLocalizedString("Localization.Menu.Toast.Preparing", tableName: nil, bundle: Bundle.main, value: "", comment: "")
                , value1)
            }
        }
    }
}